### ISSUE TITLE
Long presses aren't detected

### ISSUE THREAD

**Issue by ThaumRystra** [ThaumRystra/DiceCloud#10]
Long press events are not detected by Polymer, preventing drag and drop from being implemented on mobile.

**Comment by bhorrock** [comment]
I believe that this should be a high priority bug.   As it stands there seems to be no way to move a carried item to a container except by using the desktop.      Also, the slider/switch for equipped is 5 clicks/taps to equip and then 5 to unequip

**Comment by ThaumRystra** [comment]
Drag and drop works on all browsers now, without long press, because drag handles are used instead, but long press works if needed.
