### ISSUE TITLE
Dialog box doesn't ignore browser hotkeys

### ISSUE THREAD

**Issue by arrnonymous** [ThaumRystra/DiceCloud#139]
When I start typing within a dialog box, such as an item, a journal entry, or a feature, it activates browser hotkeys. For example: I have W and S assigned to go up and down a page, or A and D to cycle around tabs; when I do this while writing within a dialog box in Dicecloud, it will activate the hotkeys and cycle through my tabs or go up and down the page, instead of simply typing down the letters W, A, S and D.

**Comment by ThaumRystra** [comment]
Not sure if this is still relevant in #184, re-open if needed
