### ISSUE TITLE
Print a character sheet

### ISSUE THREAD

**Issue by ThaumRystra** [ThaumRystra/DiceCloud#152]
Printing a sheet is necessary for offline games, or DM's who don't allow electronics at their tables.

- [x] Stats
- [x] Proficiencies
- [x] Attacks
- [x] Traits, ideals, bonds, flaws
- [ ] Features
- [ ] Resources
- [ ] Inventory
- [ ] Spells

**Comment by ThaumRystra** [comment]
See [this branch](/ThaumRystra/DiceCloud1/tree/feature-print)

**Comment by ThaumRystra** [comment]
[This release](https://github.com/ThaumRystra/DiceCloud1/releases/tag/1.7.0) makes the first page of printing available.

**Comment by pspeter3** [comment]
I wonder if instead of generating CSS for this, it would be better to fill out the standard character sheet PDFs?

**Comment by ThaumRystra** [comment]
moved to #237 because a new implementation is needed in #184
