### ISSUE TITLE
Native Discord Support

### ISSUE THREAD

**Issue by ThaumRystra** [ThaumRystra/DiceCloud#159]
At the moment, many people are using DiceCloud with Avrae, but I believe a much better experience could be had if DiceCloud implemented its own integration with Discord.

There are two alternatives here: a Discord bot, and a Discord webhook.

## Discord bot

- A little bit complicated to implement
- Can send and receive messages from channels it has joined
- Acts like a regular Discord user, but automated
- Can't change its avatar or username with each message
- Needs to manually link each channel to a party (or DM view, when that is implemented) before it can respond with information on that party

## Discord webhook

- Can send messages to Discord, but not receive any
- Can change username and avatar with each message
- Has a unique url for each server it is activated on, so each party (or DM view) can save a webhook url

## Short term integration

Each character can save webhook URLs and use those webhooks to post its rolls, changes in health, conditions, etc. A single webhook should be active at a time.

Currently, all the stats are only known client-side, so the client needs to initiate every roll. This allows the client to cheat on their modifiers, but the roll itself can be guaranteed random, using cryptographically strong pseudo random number generation on the server.

## Long term integration

Both webhooks and a DiceCloud bot can be used. Webhooks will send messages for rolls and events instigated within DiceCloud, while the bot will be used for responding to messages.

To link Discord accounts to DiceCloud accounts, the bot will direct message the user their Discord user ID and ask them to add it to their DiceCloud account page. Their Discord ID can then be used for authentication checks the same way their Meteor.userId is used.

If the bot is asked to perform an action on a character, it can make sure that the character has the channel in its list of webhooks as basic authentication.

**Comment by haliphax** [comment]
The bot could also accept commands to roll and then push the result back through the webhook, yeah?

**Comment by ThaumRystra** [comment]
@haliphax Eventually, yes. A big requirement for that would be the server knowing the final character stats. At the moment, the server has no idea what the final values on a character sheet are, it just provides all of the information to the client, and the client builds it into a character.

**Comment by Lithial** [comment]
this seems to be basically what avrae does. am i missing anything that this would do differently?

**Comment by ThaumRystra** [comment]
Yes, this would allow you to trigger Discord messages and rolls from within DiceCloud. Avrae will always have an out-of-date character snapshot which needs to be manually updated.

**Comment by Lithial** [comment]
oh ok. I know that the current avrae lets you update and push Hitpoints and spell slots from discord. but if we can get statues and triggering rolls from dicecloud that would be really cool

**Comment by Buluphont** [comment]
Although it would not be feasible to change a bot's name/avatar for each message, do keep in mind that you can creatively use rich embed objects to fill a similar purpose.

I love the idea of pushing rolls down via webhooks!

**Comment by ThaumRystra** [comment]
Discord webhook has been implemented, reopen if a bot is needed
