### ISSUE TITLE
Share button missing on Chrome

### ISSUE THREAD

**Issue by mommothazaz123** [ThaumRystra/DiceCloud#165]
When attempting to share a character, the red "SHARE" button is missing.
Reproduced on Chrome 66.0.3359.139 on macOS 10.13.4.
![Screenshot](https://cdn.discordapp.com/attachments/263128686004404225/446495802441990144/Screen_Shot_2018-05-16_at_7.12.43_PM.png)

**Comment by ThaumRystra** [comment]
I can't reproduce this on Chrome 66 or 67. Can you confirm you are still having this issue?

**Comment by mommothazaz123** [comment]
The issue still exists on Chrome 66 on macOS, but seems fine on both Safari on macOS and Chrome 66 in Windows 10.

**Comment by ThaumRystra** [comment]
Tagging this as help wanted, I don't have a macOS device to reproduce it on. Happy to accept pull requests on this.

**Comment by PhilippeBolduc13** [comment]
I have the same issue on windows 10, chrome 69.0.3497.81
![untitled](https://user-images.githubusercontent.com/25470394/45253900-5e853d00-b33c-11e8-81a6-be0d727f8349.png)

**Comment by ThaumRystra** [comment]
As of Chrome 69.0.3497.92, can't reproduce at any screen size

**Comment by mommothazaz123** [comment]
After some investigation this looks like an issue with AdBlock, oddly; disabling it should fix it
