### ISSUE TITLE
Deleting spell list doesn't delete attacks of spells

### ISSUE THREAD

**Issue by mommothazaz123** [ThaumRystra/DiceCloud#170]
Example character ID: 9FJZEqRoontzdD82M

Steps to reproduce:
1. Create a new spell list
2. Add some spells to the spell list that grant the character attacks (e.g. Ray of Frost)
3. Delete the spell list

The attack granted by the spell that was deleted along with the spell list still appears in the character's attack list under Features; if clicked on, there are two different behaviors.

1. The deleted spell appears (likely occurs due to soft-deletion)
2. A blank card appears (likely occurs after hard-deletion)

**Comment by mommothazaz123** [comment]
A temporary solution until the issue is formally addressed is to delete the attack via your browser's JavaScript console. You'll need the name of the attack as it appears on the attack list, then follow these steps:

1. Open your browser's JavaScript console.
2. Find the ID of the attack that you want to delete (`77TKuqN6wdTucL3yt` in this example): 
```js
> Attacks.findOne({name: "NAME"})
<- e {_id: "77TKuqN6wdTucL3yt", details: "range 60 feet, target speed reduced by 10ft on hit", damage: "{floor((Level+1)/6)+1}d8", damageType: "cold", name: "Ray of Frost", …}
```
3. Delete the attack.
```js
> Attacks.remove({_id: "ID"})
<- 1
```

**Comment by ThaumRystra** [comment]
This bug is a bit broader in scope. Reproduction shows that soft-removing a node in the character tree does not actually cascade properly. So attacks, effects, etc. of items in containers are not deleted with the container containing those items.
