### ISSUE TITLE
Adding Vision Types to be cards tracked.

### ISSUE THREAD

**Issue by mcenal** [ThaumRystra/DiceCloud#173]
Adding vision type to base stats to being tracked. Also allowing for positive and negative buffs to modify stuff like that. So for example I have low-light vision, but with an artifact that I wear it is like a buff of Darkvision but it is attached to the device as I wear it and I cannot double buff it. Also when I remove the item the buff ends.

**Comment by ThaumRystra** [comment]
implemented in #184
