### ISSUE TITLE
Weapon attack names

### ISSUE THREAD

**Issue by jhumphries** [ThaumRystra/DiceCloud#179]
Right now attacks on a weapon aren't named, so it is very difficult to track which is which (e.g. 2 hand, 1 hand, off hand), especially through Avrae. Creating unique attacks can solve the problem, but maintenance becomes a mess by severing the link to the weapon itself. 

Implement naming per attack. Pre-requisite to multi-attack macros

**Comment by ThaumRystra** [comment]
All attacks are named in #184
