### ISSUE TITLE
Major Import Bug w/ Avrae

### ISSUE THREAD

**Issue by Dusk-Argentum** [ThaumRystra/DiceCloud#186]
Recently, an import bug that was few and far between with a handful of isolated cases in the past has become increasingly common. Many users on the Avrae Support Discord have been making bug reports for it. As of now, we simply tell them that it's a known bug and the best way to "fix" it is to have someone else upload their sheet and then reupload it themselves. The bug is odd, and the symptoms of it are: A discrepancy between total character HP between Dicecloud and Avrae (most common symptom), a discrepancy between the total amount for a custom counter (CC) between Dicecloud and Avrae (uncommon), and/or a discrepancy between total character spell slots between Dicecloud and Avrae (rare).
As for reproduction, it's very difficult to reproduce. Theoretically, the steps would be to make a Dicecloud sheet, throw in some numbers, upload it to Avrae, and see them all be wildly incorrect. There has not yet been a controlled reproduction of this bug, which is making it VERY hard to pin down.

**Comment by ThaumRystra** [comment]
Avrae import will need re-writing as of #184
