### ISSUE TITLE
Net Worth Calculation

### ISSUE THREAD

**Issue by TheBadW01f** [ThaumRystra/DiceCloud#189]
Dicecloud incorrectly calculates the net worth of one of my characters, but only if I have no sp or cp. If I add 1 sp, it corrects the calculation, and if I remove it the calculation reverts to its original, incorrect version, being 1 gp low. See: https://drive.google.com/file/d/15pLn4IxGZT2sPsOTVFcmLG0UGUAhd3nd/view?usp=sharing

**Comment by ThaumRystra** [comment]
Can you give me a link to the character? I don't need to have read or write access, I just need to clone its inventory so I can reproduce the problem.

**Comment by TheBadW01f** [comment]
Here is the link:
https://dicecloud.com/character/B9TkHxZqRPqNCRTM9/Olga

**Comment by ThaumRystra** [comment]
Will be fixed with #238
