### ISSUE TITLE
Inventory dragging on Firefox

### ISSUE THREAD

**Issue by MagicCraftMaster** [ThaumRystra/DiceCloud#190]
Dragging items in the inventory on Firefox does not work in any way and it would be nice if it worked correctly since myself and others prefer the browser and it's unfortunate that the drag feature is missing.

**Comment by ThaumRystra** [comment]
So the inventory drag and drop interface uses events that are supported by all browsers going back to 2009, so even though I don't go out of my way to support Firefox, there's no reason it shouldn't work.

Will try and fix.

**Comment by thislooksfun** [comment]
Can confirm that this doesn't work in FF 65.0

**Comment by FrankTrog** [comment]
Just a heads up that this issue has recently started occuring in the Brave browser Version 1.3.115 Chromium: 80.0.3987.87 (Official Build) (64-bit)

**Comment by lenzo1** [comment]
Currently having this bug on the latest version of Chrome: Version 80.0.3987.163 (Official Build) (64-bit)

**Comment by ThaumRystra** [comment]
Drag and drop re-implemented in #184, should work on all devices including mobile.
