### ISSUE TITLE
Enhancement: Folders for features

### ISSUE THREAD

**Issue by NanoSymmetry** [ThaumRystra/DiceCloud#194]
When multiclassing the features tab becomes very cluttered. The ability to add folders would make the interface far more clean and easy to use.

**Comment by ThaumRystra** [comment]
Folders will be considered in version 2, but just for reference, features only display the text before the first horizontal break in the content. So if you add `- - -` on a blank line, it will show up in the feature as a horizontal break like this:

--- 

And all the text below the break will be hidden on the feature card until it is opened. This can help neaten up cluttered features pages.
