### ISSUE TITLE
Change the order of the Base Ability Scores default feature to accurately reflect sheet order

### ISSUE THREAD

**Issue by Dusk-Argentum** [ThaumRystra/DiceCloud#196]
Currently, the Base Ability Scores feature has the scores listed in the order of "Dexterity, Constitution, Intelligence, Wisdom, Charisma, Strength". Suggested order would be the same as the order on the Stats tab of the sheet, namely "Strength, Dexterity, Constitution, Intelligence, Wisdom, Charisma", which seems to be the most common order for a lot of sheet reference material for DnD 5e.

**Comment by ThaumRystra** [comment]
Order is now enforceable in #184
