### ISSUE TITLE
Encountering "500 - Internal Server Error" when using Avrae

### ISSUE THREAD

**Issue by FrostJaeger** [ThaumRystra/DiceCloud#203]
Greetings,

I am encountering several issues when attempting to utilize Dicecloud and the Avrae plugin on Discord - specifically, attempting to "import" a character via the "!dicecloud" command and attempting to update Avrae's stored version of the sheet (via the !update command) both result in Avrae displaying the following message:

- https://i.imgur.com/7snONN0.png
- https://i.imgur.com/EFwSCGr.png

As the links below demonstrate, both character sheets are valid:

- https://dicecloud.com/character/KTQSwm63DXAQmpzrK/
- https://dicecloud.com/character/iWpJ6bkef8oMjqsRK/

Now, I am aware that this issue is not specifically related to Dicecloud or Avrae - thus I've created two GitHub issue posts, one for Dicecloud site and the other for Avrae:

- Avrae: https://github.com/avrae/avrae/issues/481 (Note: Not opened by me, but the OP is encountering an identical problem.)
- Dicecloud: https://github.com/ThaumRystra/DiceCloud/issues/203

**Comment by ThaumRystra** [comment]
Fixed in update 1.8.3
