### ISSUE TITLE
DB seems to be down

### ISSUE THREAD

**Issue by patrickherrmann** [ThaumRystra/DiceCloud#208]
The website loads, but no character data loads.

**Comment by Jtrinh3** [comment]
Not just you.

**Comment by patrickherrmann** [comment]
Anyone know where the DB is hosted?

**Comment by patrickherrmann** [comment]
Looks like it's back up. 👍

**Comment by ThaumRystra** [comment]
Database and server are both hosted in Western Europe at the moment, but with plans to move to US-East
