### ISSUE TITLE
Unable to populate library local install

### ISSUE THREAD

**Issue by SteamCrunk** [ThaumRystra/DiceCloud#209]
Admittedly I'm not the best when it comes to js stuff, but near as I can tell "SRDLibraryGA3XWsd" doesn't exist, and I'm not really sure how to make it exist.

**Comment by ThaumRystra** [comment]
You will need to insert the default library, with yourself as the owner

``` JavaScript
Libraries.insert({
  _id: "SRDLibraryGA3XWsd",
  name:    "SRD Library",
  owner:  Meteor.userId(),
});
```

**Comment by SteamCrunk** [comment]
Okay, I think that's what I was missing, I was trying to do that with node on the actual server console.  I can probably work my way from here, thanks!

**Comment by SteamCrunk** [comment]
I'm still having tons of issues getting the library populated.  srdimport.js isn't a good enough guideline on what to do, because I get errors left and right.  I'm assuming it all needs to be run in the console in the web browser.  I understand documentation for folks running it locally comes secondary to the main project, but please provide actual documentation for both populating the library after initial server setup, and then updating the library with added content.

**Comment by SteamCrunk** [comment]
Well I was able to get through, definitely some user issues on my side.  Some improved documentation would definitely be appreciated though.
