### ISSUE TITLE
Hard crash after latest updates (local install)

### ISSUE THREAD

**Issue by SteamCrunk** [ThaumRystra/DiceCloud#210]
I updated my local install with a git pull and now I can't start dicecloud at all.

W20190309-18:06:24.683(-7)? (STDERR) /home/envy/.meteor/packages/meteor-tool/.1.8.0_2.1om3lwx.sy8++os.linux.x86_64+web.browser+web.browser.legacy+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280  

W20190309-18:06:24.683(-7)? (STDERR) 						throw(ex);  

W20190309-18:06:24.683(-7)? (STDERR) 						^  

W20190309-18:06:24.683(-7)? (STDERR)   

W20190309-18:06:24.684(-7)? (STDERR) TypeError: Cannot read property 'clientId' of undefined  

W20190309-18:06:24.684(-7)? (STDERR)     at patreon.js (server/patreon/patreon.js:3:50)  

W20190309-18:06:24.684(-7)? (STDERR)     at fileEvaluate (packages/modules-runtime.js:336:7)  

W20190309-18:06:24.684(-7)? (STDERR)     at Module.require (packages/modules-runtime.js:238:14)  

W20190309-18:06:24.684(-7)? (STDERR)     at require (packages/modules-runtime.js:258:21)  

W20190309-18:06:24.684(-7)? (STDERR)     at  /home/envy/.git/external/dicecloud/app/.meteor/local/build/programs/server/app/app.js:8018:1  

W20190309-18:06:24.684(-7)? (STDERR)     at /home/envy/.git/external/dicecloud/app/.meteor/local/build/programs/server/boot.js:411:36  

W20190309-18:06:24.684(-7)? (STDERR)     at Array.forEach (<anonymous>)  

W20190309-18:06:24.684(-7)? (STDERR)     at /home/envy/.git/external/dicecloud/app/.meteor/local/build/programs/server/boot.js:220:19  

W20190309-18:06:24.684(-7)? (STDERR)     at /home/envy/.git/external/dicecloud/app/.meteor/local/build/programs/server/boot.js:471:5  

W20190309-18:06:24.684(-7)? (STDERR)     at Function.run (/home/envy/.git/external/dicecloud/app/.meteor/local/build/programs/server/profile.js:510:12)  

W20190309-18:06:24.685(-7)? (STDERR)     at /home/envy/.git/external/dicecloud/app/.meteor/local/build/programs/server/boot.js:470:11

This is what it spits out over and over when attempting to start.  Doing a fresh install elsewhere yields the same results.

**Comment by ThaumRystra** [comment]
This is related to 1.10, there was an announcement on the DiceCloud discord about waiting on updating local instances to 1.10 until it's been resolved.
