### ISSUE TITLE
NPC manager

### ISSUE THREAD

**Issue by sdaugherty** [ThaumRystra/DiceCloud#213]
A NPC manager with the following functionality:

- Create NPC from scratch, from a template, or from random values (or some combination thereof)
- Edit NPC
- Turn NPC into PC (or "loan" an NPC to a player for hirelings or for players who want to join before they've made a character)
- Manage NPC inventories
- Manage NPC attitudes towards one another and towards PCs (sometimes over a long campaign, this can get hard to keep track of)
- Create NPC templates (preferably scalable by level)
- Edit NPC templates

This would likely go along with the DM tools in the v2 roadmap.

**Comment by ThaumRystra** [comment]
Monsters and NPC's running on the DiceCloud character engine is confirmed as a 2.x feature, which will be started on some time after the 2.0 release

**Comment by ThaumRystra** [comment]
Monsters can be created in #184, but they don't have specific character sheets just yet.
