### ISSUE TITLE
Allow modules to "use" variables

### ISSUE THREAD

**Issue by HACKhalo2** [ThaumRystra/DiceCloud#222]
For instance, I set up a Sorcerer and his Flexible Casting as a spell in his spell book, and run them as buffs. Currently, I have to adjust the actual amount of points the spell slots and Sorcery Points have (so I TAKE AWAY A TOTAL of 2 points of Sorcery Points to add a total of one Level 1 spell slot, or I TAKE AWAY ONE spell slot to add a Sorcery Point.

If there was a way to adjust the expended part of certain systems (like spell slots, sorcery points, ki, etc) instead of just adjusting the total points overall, that would be amazing

**Comment by ThaumRystra** [comment]
This will be the case in version 2 where actions can directly cost resources to use.

**Comment by ThaumRystra** [comment]
See #241
