### ISSUE TITLE
Add a list to the stats page of custom buffs

### ISSUE THREAD

**Issue by swordglowsblue** [ThaumRystra/DiceCloud#229]
Conditions are extremely easy to apply to yourself - just click the plus, select the condition, and hit OK. Buffs, however, are not so streamlined. To use a buff defined by a spell, for example, you need to go to your spellbook, find the specific spell, open the spell's card, click "apply to self", exit the card, and return to the stats screen. It would be extremely useful in my opinion to have a "buff library" view on the stats screen, similar to what exists for conditions, which lists all of your defined buffs and allows you to easily access / apply them. As is, I find myself hesitating to even use the buff system at all, since I'm not personally using the party features and so buffs become more of a concise way of tracking spell effects on myself than anything else. I'd love to define buffs for the effects of spells like _disguise self_ or _mirror image_, but the current system is so clunky that it's not really worth the effort of using them once they're set up.

**Comment by ThaumRystra** [comment]
Buffs are handled in a more automated fashion in #184. Will be fixed with #241
