### ISSUE TITLE
Dicecloud automatically puts number when I want text.

### ISSUE THREAD

**Issue by maaagdonals** [ThaumRystra/DiceCloud#230]
So I was experimenting with the feature tab, and I wanted to use the conditional text visibility in a way that if the character had reached a certain level, it would display a description of the class ability, and if not, to display the text "This feature is available at level X."

An example for the Barbarian's "Brutal Critical" at level 9
`{if (Barbarianlevel >= 9, "You can roll " + if(BarbarianLevel >= 17, 3, if (BarbarianLevel >= 13, 2, if(BarbarianLevel >= 9, 1, 0))) + " additional weapon damage die when determining the extra damage for a critical hit with a melee attack.", "This feature is available at level 9")}`
When I tried it, it mostly worked. However, I won't get the "This feature is available at level 9," but a "This feature is available at (insert actual Level) 9."
Is this a bug or is there anything I should put so it actually displays the word "level?"

**Comment by ThaumRystra** [comment]
This is a bug with the way variables are handled, level is replaced with its value without considering its context. In this case it is part of a string of text and shouldn't be replaced at all. You can workaround this by escaping the word level somehow, perhaps: `...available at lev" + "el 9"`

**Comment by ThaumRystra** [comment]
fixed in #184
