### ISSUE TITLE
Self-declared Variabl

### ISSUE THREAD

**Issue by 6etacat** [ThaumRystra/DiceCloud#231]
I'm multiclassing, and spell slot calculation is slightly different. So I would need to calculate a total spell casting level and determine my spell slots from that. Currently, I added a "Multiclassing" class of level 0 and sets spell slots there. If I add a new class, I would need to modify 9 effects in that class. 

If we are able to set a variable of `SpellCastingLevel = <X>Level + <Y>Level ... `, I would only need to modify one field. 

By the way, I have experience in writing Javascript, Python, C, Java, and Go. I also have some experience in design. If you need help, I'd be happy to help add some extra features or help redesign the user interface (more streamlined interaction).

**Comment by ThaumRystra** [comment]
This should be fixed by #184

**Comment by 6etacat** [comment]
Is that in v2 or the current online one?

**Comment by ThaumRystra** [comment]
No, the master branch is the currently deployed site. Version 2 will be deployed (either to the main site, or perhaps beta.dicecloud.com) when that pull request is merged.

**Comment by 6etacat** [comment]
Oh. That's awesome. So how would I declare a variable?

**Comment by ThaumRystra** [comment]
closed by #184. For specific help on using version 2 beta, you'll need to ask on the Discord server: https://discord.gg/qEvdfeB
