### ISSUE TITLE
Character-wide ordering of properties (depth first order of the tree)

### ISSUE THREAD

**Issue by ThaumRystra** [ThaumRystra/DiceCloud#236]
The character sheet or view should do a depth-first walk of the creature tree, creating an order object of the form `{[_id]: absoluteOrderNumber}` and refer to that order to sort each list before display.

**Comment by meyercm** [comment]
Is this the reason that the Ability Scores are in a bizarre order?

**Comment by ThaumRystra** [comment]
> Is this the reason that the Ability Scores are in a bizarre order?

No, this refers to version 2, the ability score base values being unordered is a v1 problem
