### ISSUE TITLE
Missing Speed Types

### ISSUE THREAD

**Issue by drag0n4rtist7** [ThaumRystra/DiceCloud#244]
I really enjoy this site, and it is one of my favourite ones to use for making character sheets online, but one of the things that I find most annoying is having to deal with not having all your speed types down. Currently, all that is available is just speed, which generally translates to walking speed, but I have several characters that also have swimming speeds, and a few with climbing and flying speeds, too. The problem I am facing is that I can only have walking speed displayed on the main page, and none of my other speeds. If this already exists, I will be happy to learn how to show this.

**Comment by ThaumRystra** [comment]
Fixed in #184
