### ISSUE TITLE
Add Dice Roller

### ISSUE THREAD

**Issue by meyercm** [ThaumRystra/DiceCloud#245]
Would be excellent to have a dice roller right on the Charachter Sheet, similar to a popular char sheet website, that rolls and applies the appropriate modifiers.  Useful enhancements might be a dice menu in the corner and advantage/disadvantage options on appropriate rolls.  Adding Roll history would be excellent to be able to play remote and have some 'proof-of-roll' for the DM.

loving the site, and the concept.

**Comment by SomeCallMeTom** [comment]
[https://codepen.io/antiochIst/pen/qBWNajp](url)

**Comment by ThaumRystra** [comment]
fixed in #184
