### ISSUE TITLE
Library options for Race/Class/subclass

### ISSUE THREAD

**Issue by meyercm** [ThaumRystra/DiceCloud#246]
Would appreciate the speed gain of being able to pull races, classes, and subclass features from a library, similar to how weapons work.

I get the design goal of having perfect flexibility, and part of me appreciates the familiarity needed to input all the features of a race/class, but I often just want to create a throwaway for a one-off or a minion NPC without having to do any drugery.

**Comment by ChellieH** [comment]
This is a feature in the beta for version 2. If you join the discord people have already started compiling libraries for the things you seek (if you have access to the beta)

**Comment by ThaumRystra** [comment]
fixed in #184
