### ISSUE TITLE
Add a way of distinguishing between known and prepared spells.

### ISSUE THREAD

**Issue by ChellieH** [ThaumRystra/DiceCloud#248]
I really like the functionality of the spells page but was wondering if there would be a way of distinguishing known spells and prepared spells on one spell list as only half of the base classes 'prepare' spells. 

Selecting prepared spells feels weird as a Sorcerer but if you use the always prepared feature you show as having 0/5 spells (I use the max prepared formula to keep track of how many I can know). I do appreciate this is kind of a fluffy rpg request.

The only ideas I came up with were having an additional check box for known spells or changing the wording from 'Prepared' to 'Available to Cast'

**Comment by ThaumRystra** [comment]
When using Libraries of Vexus, this is handled by having known spells in the appropriate slot, which should limit spells known correctly.

Closing this, as it's now a library's responsibility to implement.
