### ISSUE TITLE
Spell drag-drop doesn't work

### ISSUE THREAD

**Issue by asilano** [ThaumRystra/DiceCloud#250]
Since Cantrips and levelled spells work differently (Cantrips are always known and prepared; most classes have access to more spells than they prepare at once), I created two spell lists: one called "Wizard Cantrips", one called "Wizard Spells". Adding spells puts them in the first list by default (I can live with that).

**I expected**: to be able to drag a spell between lists

**Actual behaviour**: can't drag spells (the spell's block is picked up by the cursor, but the pointer shows the "can't drop here" crossed-circle)

I see this was already addressed by #105 (PR #120) - is this a regression? Did it not ship to dicecloud.com? Or am I doing something wrong?

**Comment by ThaumRystra** [comment]
Native drag and drop is continuously broken by browsers, #184 abandons native drag and drop entirely, so this is essentially fixed.
