### ISSUE TITLE
RogueLevel code not working

### ISSUE THREAD

**Issue by windsocktier** [ThaumRystra/DiceCloud#263]
![9F0A9347-729F-4D75-B23B-6CF7F7BB3923](https://user-images.githubusercontent.com/79376459/108606139-356e9080-736d-11eb-848b-27ba0fb3ef61.jpeg)
I’ve had no issues with any of the other classes I’ve made, but for whatever reason, Rogue seems to be absent in the code—unless I’m missing something here.

**Comment by Ganonslayer** [comment]
The names for the classes aren't built into the code. They're created when you add a level in that class. Double check that you spelled rogue correctly when you added that class level. For this variable name, it should be spelled "Rogue".

**Comment by ThaumRystra** [comment]
> The names for the classes aren't built into the code. They're created when you add a level in that class. Double check that you spelled rogue correctly when you added that class level. For this variable name, it should be spelled "Rogue".
