### ISSUE TITLE
A way to choose what parts of an action show up on the log

### ISSUE THREAD

**Issue by M1tht1c** [ThaumRystra/DiceCloud#271]
It would be nice to have a way to hide certain things like conditions from the log, as often I might have an ability with several different conditions for things like checking the spell level and all that for example: I have a mystic whose spells need a bunch of conditions to make sure I'm not casting at the wrong level and all that, and its log looks like this:

>Psychic Parry
>As a reaction when you make an Intelligence, a Wisdom, or a Charisma saving throw, you gain a +2 bonus to that saving throw >for each psi point you spend. You can use this ability after rolling the die but before applying the result slotLevel
>
>Psi Points available
>psiPoints >= slotLevel = true
>
>is being cast at available level
>slotLevel <= 3 = false
>
>Is above appropriate level
>slotLevel >= 4 = true
>
>is level 4
>slotLevel == 4 = false
.......

So it would be nice if there was an option to hide all the conditionals and just show something like: "cannot cast at this level"

**Comment by ThaumRystra** [comment]
All action-activated properties should now have "Don't show in log" as an option
