### ISSUE TITLE
Trouble Adding the SRD library

### ISSUE THREAD

**Issue by george-andr** [ThaumRystra/DiceCloud#279]
I am trying to self host dicecloud but when I run:

>>id = Libraries.insert({
    _id: "SRDLibraryGA3XWsd",
    owner: Meteor.userId(),
    name: "SRD Library",
});

I get an error saying Libraries is not defined. Any Ideas?

**Comment by ThaumRystra** [comment]
Just to confirm, you are running the master branch? This procedure is no longer valid in https://github.com/ThaumRystra/DiceCloud/tree/version-2

**Comment by george-andr** [comment]
I am not sure. I cloned the repository referenced in "Getting Started" using `git clone https://github.com/ThaumRystra/DiceCloud dicecloud`.

**Comment by george-andr** [comment]
It turns out that I was using version-2 instead of the master branch. Tested with master and everything works fine.
