### ISSUE TITLE
Bug: Scimitar defaults only account for strength mods

### ISSUE THREAD

**Issue by jpmmcneill** [ThaumRystra/DiceCloud#280]
Despite the scimitar being a finesse weapon (https://www.dndbeyond.com/equipment/scimitar) meaning either dex or strength can be used, when a scimitar is imported from the inbuilt item list it only uses strength.

**Comment by jpmmcneill** [comment]
@ThaumRystra hey 👋

A friend showed me this tool and it's really neat! I spotted this tiny bug when setting up a character and reckoned I could fix it pretty easily. I might be requesting to merge into the wrong branch, if so please let me know!

**Comment by ThaumRystra** [comment]
Fixed in version 2
