### ISSUE TITLE
Features become invisible at certain zoom levels

### ISSUE THREAD

**Issue by benjaminglass1** [ThaumRystra/DiceCloud#287]
At certain zoom levels (including the default zoom level on my monitor), certain entries on the "Features" tab become invisible (as in, not accessible via scrolling or otherwise). See the screenshots below, particularly the grey entries at the end. The first screenshot was 100% zoom, the second 90%:

![Screenshot 2021-10-31 at 17-37-57 Baharoosh Rivaan](https://user-images.githubusercontent.com/3344239/139603547-84ad2f14-5fb2-4496-845a-20133dd634b4.png)

![Screenshot 2021-10-31 at 17-38-15 Baharoosh Rivaan](https://user-images.githubusercontent.com/3344239/139603549-82ebd4c5-f03a-42e0-b823-b83566249063.png)

**Comment by ThaumRystra** [comment]
Version 2 is out, if this issue still appears on the new version, please re-open
