### ISSUE TITLE
Multiple features using the same pool

### ISSUE THREAD

**Issue by MendesLL** [ThaumRystra/DiceCloud#291]
Would be good to add a field when creating features, like the "limited uses" field, but to turn these limited uses common to other features. 

I am playing a circle of stars' druid, and it gives both 2 uses of guiding bolt as a slotless spell, and the Starry Form shares it's uses pool with Wild Shape. It would be very usefull for the ability to create a use tracker both on the features and spell page, and features page. 

The spells one might as well be like the spell slots counter we already have, the difference is that one should create it by enabling a spell to have "unslotted uses" and how many uses, so a tracker with the spell's name appear.

The features one might just be implemented as this: 
When creating a limited uses feature ( like wild shape) there may be a"common pool" drop down menu that is default "not", but once turned to "pool" will create a variable instance exposed for the user (since there may be a possibility for a feature to have, lets say, WildShapeUses+something) with it's name being generated from the feature name (like WildShapeUses) and displayed for the user anywhere in the definition of the original feature that will pass on max uses and current uses to "syphoning" features.
And there should be a formula field once you turn a feature to "syphoning", where you put the "pool" variable name and it will retrieve the max uses and retrieve and edit current uses.

_Please label this as enhancement and any other category that is fit_

**Comment by ThaumRystra** [comment]
This is supported in version 2 with resources used
![image](https://user-images.githubusercontent.com/9525416/205436980-3ca68b70-1930-49c5-b961-2beb35235af8.png)
