### ISSUE TITLE
DiceCloud down?

### ISSUE THREAD

**Issue by joshuathelillie** [ThaumRystra/DiceCloud#293]
As of April 2022, www.dicecloud.com appears to be down. It appears to have been down for at least several days now.

- https://downforeveryoneorjustme.com/dicecloud.com
- https://isitdownorjust.me/dicecloud-com/
- https://www.saashub.com/dicecloud-status

Is there a simple solution to this issue? I have a sizable group using DiceCloud heavily with plans to play in the near future.

Thank you.

**Comment by ThaumRystra** [comment]
DiceCloud's DNS settings were invalidated by an issue with the hosting provider, it was down for around 7 hours but fixing DNS issues may have taken up to 24 hours to propagate. My own uptime monitoring has the downtime as 11h 23m. 

All is well now.
