### ISSUE TITLE
Documentation for the API?

### ISSUE THREAD

**Issue by shaielc** [ThaumRystra/DiceCloud#294]
Hi, is there any place with documentation for the API, WebSocket, etc?

Or more specifically JSON schema for the character export?
the one at "/character/<char_id>/json"

**Comment by flashkid10** [comment]
Hi, I second this, I want to see if I'm able to build more tools
but I don't have much in ways of documentation

**Comment by ThaumRystra** [comment]
API is not stable nor supported just yet, docs will be added along with more API endpoints some time before 2.1

**Comment by ThaumRystra** [comment]
https://dicecloud.com/docs/api
