### ISSUE TITLE
Hanging after running meteor

### ISSUE THREAD

**Issue by xXAquaNightXx** [ThaumRystra/DiceCloud#295]
=> Started proxy.
=> Meteor 2.7.3 is available. Check the changelog https://docs.meteor.com/changelog.html and update this project with 'meteor update'.
=> Started MongoDB.
   Extracting zer0th:meteor-vuetify-load...

I get up to here following the install guide to run offline , on windows 10

**Comment by Scahry** [comment]
how did you fix it?

edit: ok, it just takes a very long time
