### ISSUE TITLE
Can't add languages

### ISSUE THREAD

**Issue by Zakini** [ThaumRystra/DiceCloud#296]
The languages card on the persona tab isn't clickable, so there's no way of adding which languages a character speaks.

At a glance, it looks like that card is missing the `characterField` class.

**Comment by Tzalumen** [comment]
I thought this was an issue at first, but it's one of location. 
Languages are added as proficiencies to the entries for race, class, and background.

**Comment by ThaumRystra** [comment]
skill issue ;)
