### ISSUE TITLE
Discord is eventually going kill this project.

### ISSUE THREAD

**Issue by russ-go** [ThaumRystra/DiceCloud#298]
ISSUE:
Discord is gatekeeping participation in you project and that really sucks.
I was super stoked to get involved with DiceCloud but because I don't have a mobile phone I can't discord to talk to devs and participate in adding library content.

SUGGESTED SOLUTION:
- Preferably migrate to privacy and security minded F/OSS messaging platform.  [matrix], rocket.chat, etc

I know it's a big ask as Discord does the hosting and communications.  But if I can't communicate with you guys is it working?

**Comment by pb-413** [comment]
Wow, I never thought about it that way. 

They have a web app and a Windows app (and I presume other desktop versions). Have you tried out those?

**Comment by KatrinaKitten** [comment]
Discord has an in-browser version as well as desktop apps for every major OS, and is completely free (as in free beer) to use. FOSS alternatives are great, but they gatekeep participation for the average user *far* more than Discord by every measure; the vast majority of people neither know nor care about FOSS alternatives, and Discord is a more widely known and trusted name.

**Comment by ThaumRystra** [comment]
What precisely would a FOSS communication platform offer that Discord does not? The DiceCloud server is a public forum, so privacy of your posted messages is already moot. You can use their web app with a decent browser preventing them from gathering any of your personal information, and it works on desktop, so a lack of mobile device isn't an impediment.

Apart from the vibes of sticking to FOSS software, what other advantages are there to moving off Discord as a platform?

**Comment by ThaumRystra** [comment]
Wont fix
