### ISSUE TITLE
Characters from Version 1 not appearing in Version 2

### ISSUE THREAD

**Issue by zarthross** [ThaumRystra/DiceCloud#305]
![image](https://user-images.githubusercontent.com/1111592/205469430-996769c3-8dac-4aaa-bdf4-e9fe3886a4fb.png)

My display shows a bunch of random characters at the top right, and I seem to have lost access to my characters that were in version 1 after the update to version 2....

Is there a way to recover them?

**Comment by ThaumRystra** [comment]
https://v1.dicecloud.com

**Comment by zarthross** [comment]
Thanks.
