### ISSUE TITLE
Wiki for documentation and usability

### ISSUE THREAD

**Issue by ThaumRystra** [ThaumRystra/DiceCloud#35]
Using this github project's wiki is probably going to be the easiest way to manage usability information

**Comment by ThaumRystra** [comment]
This formula list can be added to the wiki

**Comment by Araevin** [comment]
I converted the [dicecloud helper document](https://docs.google.com/spreadsheets/d/1UfZ9e9Z9XFiZ7uapyDxrh9UskZSmPGa-nWr7mCqzevw/edit#gid=2049461169) to markdown and created a wiki page [here](https://github.com/ThaumRystra/DiceCloud/wiki/DiceCloud-Helper-Equations)

**Comment by ThaumRystra** [comment]
Contributing help documents for v1 is no longer a good use of effort, see #234
