### ISSUE TITLE
New/Temp HP bar on Tablet/Mobile missing buttons to Cancel/Save

### ISSUE THREAD

**Issue by mraichelson** [ThaumRystra/DiceCloud#61]
When using DiceCloud on a tablet the lightboxed pane for adding a new hit point bar to track temporary hit points doesn't included the buttons necessary to add the bar to the page.

Clicking outside the lightbox does close the overlay but the values don't get saved or added to the character sheet.

![7e033fd2-0f3b-44f6-bcb1-3de5bc8cfe78 large](https://cloud.githubusercontent.com/assets/70476/25672215/41b28af2-2ff8-11e7-80c8-96797671a9e5.JPG)

**Comment by mraichelson** [comment]
Mobile screenshot.

![img_3151](https://cloud.githubusercontent.com/assets/70476/25672330/b14eaff8-2ff8-11e7-8c44-0568a399e6ee.PNG)

**Comment by ThaumRystra** [comment]
Specific to iOS devices, I don't have a device to bugfix this on at the moment.

**Comment by ThaumRystra** [comment]
fixed in v2
