### ISSUE TITLE
Can't sign in on iPad/Safari

### ISSUE THREAD

**Issue by ThaumRystra** [ThaumRystra/DiceCloud#67]
Sign-in button unresponsive

**Comment by phishen** [comment]
I’m using on iPad right now

**Comment by phishen** [comment]
Not sure what happened but when I opened my iPad today I was logged out and now can’t log back in. Pressing the log in button does not appear to have any visible effect. Same device as before: iPad mini 4 with iOS 11.2.5. 

Additionally I can’t sign in on my iPhone X running iOS 11.3.1. I tried Safari and Chrome.
