### ISSUE TITLE
Many proficiencies make editing dialogs slow to open

### ISSUE THREAD

**Issue by ThaumRystra** [ThaumRystra/DiceCloud#73]

**Comment by Dumbgenius** [comment]
I disagree with this - adding a proficiency is simple enough currently that adding a dialog would probably slow everything down for the user, especially when dealing with adding a class that has a whole bunch of proficiencies (like the Rogue).

The only advantage I see to this is it means that the proficiency list can be sorted without the individual proficiencies moving around while the user is trying to edit them.

**Comment by ThaumRystra** [comment]
One of the drivers here is the slow performance of Blaze and Polymer when building a template with many dropdown menus. If you have a rogue with a bunch of proficiencies, there is a distinct freeze when pulling up the edit dialog.

Maybe the issue should be renamed to the actual problem, rather than the assumed solution

**Comment by ThaumRystra** [comment]
fixed in #184
