### ISSUE TITLE
Add long and short rest buttons

### ISSUE THREAD

**Issue by ThaumRystra** [ThaumRystra/DiceCloud#87]
A "long rest" should have a number of actions that alter the character. There should be a big notification of resting occurring so that you don't accidentally rest twice.

Some default ones: 

- Reset hitpoints
- Give half hit dice back
- Reset all features marked with "reset on long rest"

**Comment by christhekeele** [comment]
Short rests would be tricky as they can partially restore spell slots. Although one hacky solution would be to create two different sets of `+N spell slots` for each slot level and flag one as both long and short-restable.

**Comment by ThaumRystra** [comment]
Yeah, so the idea is that you can set an attribute to reset on a short or long rest, but then also be able to attach other actions to rests, like restoring 2 level 2 spell slots on a short rest, or recovering half your hit dice, for the specific cases where things aren't reset entirely.

**Comment by SirTomOfCanada** [comment]
Would you add a section to Class for this & have the switches on the stats page?

**Comment by SirTomOfCanada** [comment]
Would you add a section to Class for this & have the switches on the stats page?

I think you might want to use two mouse clicks... Or an undo, which sounds much more difficult.

**Comment by christhekeele** [comment]
I think you'd want to allow attaching the 'recoverable via rest' feature to pretty much thing that you can attach an attack or buff to today.

I agree that the stats page feels like the best place for the 'I've rested' buttons, perhaps inside the hit dice widget (to help you remember to use them for short rests).

**Comment by Bazzu85** [comment]
any news about this usefull function?

**Comment by christhekeele** [comment]
❤️ 💜 💙 💚 💛 🧡 ❤️

**Comment by ThaumRystra** [comment]
Only 3 years later 😂

**Comment by SomeCallMeTom** [comment]
We love ya for it tho
