### ISSUE TITLE
Export/Import feature for Dicecloud instances

### ISSUE THREAD

**Issue by TheFiZi** [ThaumRystra/DiceCloud#99]
Ability to export/import characters from one instance of Dicecloud to another.

Helps if people want to move from the hosted version to a self-hosted version. Also a good way to backup their character themselves.

**Comment by ThaumRystra** [comment]
I'll be happy to accept pull requests on this if it's needed. Should be as simple as iterating through the collections a character uses and serializing every document with the right `charId`, then deserializing it on the other instance. 

DiceCloud does have nightly backups of the entire database, but I can understand wanting to make your own backups.

**Comment by mcenal** [comment]
Also if it can be done online as well, IE/ from one account to another (duplicate) or from one account to itself (templating.) For example I want to manage all the NPCs in my campaign similar to PCs, but sometimes I need Thug 1, 2, 3, 4 to keep track of things such as HP, buffs and other things.

**Comment by ThaumRystra** [comment]
The core of this issue is resolved with the ability to upload and download v2 character archives.
